### ISSUE TITLE
Prepare DRAFT Milestones and Deliverables Document

### ISSUE THREAD

**Issue by timclark** [force11/force11-dcig#3]
A DRAFT Milestones a Deliverables document should be prepared, initially based on the "Proposed Deliverables" in this document: http://bit.ly/1jOCEHk, as discussed on the April 14 concall.  The document should show relationships of proposed deliverables to practical and usable outcomes for publishers and repositories.

**Comment by Klortho** [comment]
Closing -- please re-open if you disagree.
